#!/usr/bin/env python3
#
# Compare MooncakeConnector KV cache dumps generated by
# VLLM_ASCEND_MOONCAKE_KV_DUMP_DIR.
#
# This script is intentionally standalone and is not part of the linted code
# path. It is meant for field debugging.

from __future__ import annotations

import argparse
import json
import os
from collections import defaultdict
from dataclasses import dataclass
from typing import Any

import torch


@dataclass
class DumpEntry:
    json_path: str
    tensor_path: str
    side: str
    stage: str
    request_id: str
    rank: int
    layer_idx: int
    layer_name: str
    cache_idx: int
    block_ids: tuple[int, ...]
    record: dict[str, Any]
    stats: dict[str, Any]

    @property
    def compare_key(self) -> tuple[Any, ...]:
        return (
            self.request_id,
            self.layer_idx,
            self.cache_idx,
            self.record.get("group_idx"),
            self.record.get("remote_tp_offset"),
            self.record.get("prefill_pp_rank"),
            self.record.get("is_mamba_group"),
        )


def load_entries(dump_dir: str) -> list[DumpEntry]:
    entries = []
    for name in sorted(os.listdir(dump_dir)):
        if not name.endswith(".json"):
            continue
        json_path = os.path.join(dump_dir, name)
        with open(json_path, encoding="utf-8") as f:
            meta = json.load(f)
        tensor_path = meta.get("tensor_file", "")
        if not os.path.isabs(tensor_path):
            tensor_path = os.path.join(dump_dir, tensor_path)
        if not os.path.exists(tensor_path):
            print(f"[WARN] tensor file missing for {json_path}: {tensor_path}")
            continue
        entries.append(
            DumpEntry(
                json_path=json_path,
                tensor_path=tensor_path,
                side=meta["side"],
                stage=meta["stage"],
                request_id=meta["request_id"],
                rank=int(meta["rank"]),
                layer_idx=int(meta["layer_idx"]),
                layer_name=meta["layer_name"],
                cache_idx=int(meta["cache_idx"]),
                block_ids=tuple(meta.get("block_ids", [])),
                record=meta.get("record", {}),
                stats=meta.get("stats", {}),
            )
        )
    return entries


def filter_entries(
    entries: list[DumpEntry],
    request_id: str | None,
    layer_idx: int | None,
    cache_idx: int | None,
) -> list[DumpEntry]:
    result = []
    for entry in entries:
        if request_id is not None and entry.request_id != request_id:
            continue
        if layer_idx is not None and entry.layer_idx != layer_idx:
            continue
        if cache_idx is not None and entry.cache_idx != cache_idx:
            continue
        result.append(entry)
    return result


def group_entries(entries: list[DumpEntry]) -> dict[tuple[Any, ...], dict[str, list[DumpEntry]]]:
    grouped: dict[tuple[Any, ...], dict[str, list[DumpEntry]]] = defaultdict(lambda: defaultdict(list))
    for entry in entries:
        grouped[entry.compare_key][entry.stage].append(entry)
    return grouped


def short_path(path: str, base: str) -> str:
    try:
        return os.path.relpath(path, base)
    except ValueError:
        return path


def tensor_stats(tensor: torch.Tensor) -> dict[str, float]:
    data = tensor.detach().float().cpu()
    if data.numel() == 0:
        return {}
    return {
        "sum": float(data.sum().item()),
        "mean": float(data.mean().item()),
        "min": float(data.min().item()),
        "max": float(data.max().item()),
        "std": float(data.std(unbiased=False).item()),
    }


def compare_pair(
    p_entry: DumpEntry,
    d_entry: DumpEntry,
    dump_dir: str,
    atol: float,
    rtol: float,
    print_topk: int,
) -> bool:
    p_tensor = torch.load(p_entry.tensor_path, map_location="cpu")
    d_tensor = torch.load(d_entry.tensor_path, map_location="cpu")
    print(
        "\n"
        f"[PAIR] req={p_entry.request_id} layer={p_entry.layer_idx} cache={p_entry.cache_idx} "
        f"group={p_entry.record.get('group_idx')} remote_tp_offset={p_entry.record.get('remote_tp_offset')} "
        f"stage={d_entry.stage}"
    )
    print(f"  P: {short_path(p_entry.tensor_path, dump_dir)} blocks={list(p_entry.block_ids)} shape={tuple(p_tensor.shape)}")
    print(f"  D: {short_path(d_entry.tensor_path, dump_dir)} blocks={list(d_entry.block_ids)} shape={tuple(d_tensor.shape)}")

    if tuple(p_tensor.shape) != tuple(d_tensor.shape):
        print("  RESULT: SHAPE_MISMATCH")
        print(f"  P stats: {tensor_stats(p_tensor)}")
        print(f"  D stats: {tensor_stats(d_tensor)}")
        return False

    p_float = p_tensor.detach().float().cpu()
    d_float = d_tensor.detach().float().cpu()
    diff = (p_float - d_float).abs()
    max_diff = float(diff.max().item()) if diff.numel() else 0.0
    mean_diff = float(diff.mean().item()) if diff.numel() else 0.0
    allclose = torch.allclose(p_float, d_float, atol=atol, rtol=rtol)
    print(f"  RESULT: {'MATCH' if allclose else 'DIFF'} atol={atol} rtol={rtol}")
    print(f"  abs_diff: max={max_diff:.8g} mean={mean_diff:.8g}")
    print(f"  P stats: {tensor_stats(p_tensor)}")
    print(f"  D stats: {tensor_stats(d_tensor)}")

    if not allclose and print_topk > 0 and diff.numel() > 0:
        flat_diff = diff.reshape(-1)
        topk = min(print_topk, flat_diff.numel())
        values, indices = torch.topk(flat_diff, topk)
        print(f"  top{topk} diffs:")
        for value, flat_idx in zip(values.tolist(), indices.tolist()):
            idx = tuple(int(i) for i in torch.unravel_index(torch.tensor(flat_idx), diff.shape))
            p_value = float(p_float[idx].item())
            d_value = float(d_float[idx].item())
            allowed = atol + rtol * abs(d_value)
            print(f"    idx={idx} p={p_value:.8g} d={d_value:.8g} abs={value:.8g} allowed={allowed:.8g}")
    return bool(allclose)


def choose_latest(entries: list[DumpEntry]) -> DumpEntry:
    return max(entries, key=lambda entry: os.path.getmtime(entry.json_path))


def compare_entries(
    entries: list[DumpEntry],
    dump_dir: str,
    d_stage: str,
    atol: float,
    rtol: float,
    print_topk: int,
) -> int:
    grouped = group_entries(entries)
    matched = 0
    failed = 0
    missing = 0
    for key, stages in sorted(grouped.items(), key=lambda item: item[0]):
        p_stage = "send_before_read" if stages.get("send_before_read") else "send"
        p_entries = stages.get(p_stage, [])
        d_entries = stages.get(d_stage, [])
        if not p_entries or not d_entries:
            if p_entries or d_entries:
                print(f"\n[MISSING] key={key} p_{p_stage}={len(p_entries)} d_{d_stage}={len(d_entries)}")
                missing += 1
            continue
        p_entry = choose_latest(p_entries)
        d_entry = choose_latest(d_entries)
        matched += 1
        if not compare_pair(p_entry, d_entry, dump_dir, atol, rtol, print_topk):
            failed += 1
    print("\n[SUMMARY]")
    print(f"  pairs={matched} failed={failed} missing={missing} stage={d_stage}")
    return 1 if failed or matched == 0 else 0


def print_inventory(entries: list[DumpEntry], dump_dir: str) -> None:
    print("[INVENTORY]")
    for entry in entries:
        print(
            f"  side={entry.side} stage={entry.stage} req={entry.request_id} rank={entry.rank} "
            f"layer={entry.layer_idx} cache={entry.cache_idx} blocks={list(entry.block_ids)} "
            f"file={short_path(entry.tensor_path, dump_dir)}"
        )


def main() -> int:
    parser = argparse.ArgumentParser(description="Compare Mooncake P/D KV cache dump tensors.")
    parser.add_argument("dump_dir", help="Directory set by VLLM_ASCEND_MOONCAKE_KV_DUMP_DIR")
    parser.add_argument("--stage", choices=["recv_raw", "recv_final"], default="recv_raw")
    parser.add_argument("--request-id")
    parser.add_argument("--layer-idx", type=int)
    parser.add_argument("--cache-idx", type=int)
    parser.add_argument("--atol", type=float, default=0.0)
    parser.add_argument("--rtol", type=float, default=0.0)
    parser.add_argument("--topk", type=int, default=8, help="Print top-k element diffs for mismatched tensors.")
    parser.add_argument("--inventory", action="store_true", help="Only list dump files after filtering.")
    args = parser.parse_args()

    if not os.path.isdir(args.dump_dir):
        raise SystemExit(f"dump_dir does not exist: {args.dump_dir}")
    entries = load_entries(args.dump_dir)
    entries = filter_entries(entries, args.request_id, args.layer_idx, args.cache_idx)
    if not entries:
        raise SystemExit("No dump entries found after filtering.")
    if args.inventory:
        print_inventory(entries, args.dump_dir)
        return 0
    return compare_entries(entries, args.dump_dir, args.stage, args.atol, args.rtol, args.topk)


if __name__ == "__main__":
    raise SystemExit(main())
